basePath: /api
definitions:
  controller.downloadSuccess:
    properties:
      filename:
        type: string
      size:
        type: integer
    type: object
  controller.errorMessage:
    properties:
      error:
        type: string
    type: object
  controller.successMessage:
    properties:
      success:
        type: string
    type: object
  entity.Affiliate:
    properties:
      created_at:
        type: string
      filename:
        type: string
      id:
        type: integer
      object_id:
        type: string
      post_refer:
        type: integer
      updated_at:
        type: string
    type: object
  entity.Post:
    properties:
      affiliates:
        items:
          $ref: '#/definitions/entity.Affiliate'
        type: array
      content:
        type: string
      created_at:
        type: string
      date:
        type: string
      id:
        type: integer
      subtitle:
        type: string
      tags:
        items:
          $ref: '#/definitions/entity.Tag'
        type: array
      title:
        type: string
      updated_at:
        type: string
    type: object
  entity.Tag:
    properties:
      color:
        type: string
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      name:
        type: string
      posts:
        items:
          $ref: '#/definitions/entity.Post'
        type: array
      updated_at:
        type: string
    type: object
host: localhost:8080
info:
  contact:
    email: jacobbishopxy@gmail.com
    name: Jacob Bishop
    url: https://github.com/Jacobbishopxy
  description: A simple toy-note API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
  title: Toy-note API
  version: "1.0"
paths:
  /delete-post/{id}:
    delete:
      description: delete a post by ID
      parameters:
      - description: post ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.successMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.errorMessage'
      summary: delete a post by ID
      tags:
      - post
  /delete-tag/{id}:
    delete:
      description: delete a tag by ID
      parameters:
      - description: tag ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.successMessage'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.errorMessage'
      summary: delete a tag by ID
      tags:
      - tag
  /download-file:
    get:
      description: download an affiliate by ID
      parameters:
      - description: affiliate ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controller.downloadSuccess'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controller.errorMessage'
      summary: download an affiliate by ID
      tags:
      - affiliate
  /get-posts:
    get:
      description: get all posts
      parameters:
      - description: page number
        in: query
        name: page
        required: true
        type: integer
      - description: page size
        in: query
        name: size
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Post'
            type: array
      summary: get all posts
      tags:
      - post
  /get-tags:
    get:
      description: get all tags
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Tag'
            type: array
      summary: get all tags
      tags:
      - tag
  /save-post:
    post:
      consumes:
      - multipart/form-data
      description: |-
        Save post can be used to create a new post or update an existing post.
        If id is not provided, it will create a new post; Otherwise, it will update an existing post.
        Form-data should also be provided if the post has any new affiliate.
      parameters:
      - description: post data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.Post'
      - description: affiliate files
        in: formData
        name: files
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Post'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.errorMessage'
      summary: create/update a post
      tags:
      - post
  /save-tag:
    post:
      description: create a new tag or update an existing tag, based on whether the
        tag ID is provided
      parameters:
      - description: tag data
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/entity.Tag'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.Tag'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/controller.errorMessage'
      summary: create/update a tag
      tags:
      - tag
  /search-posts-by-tags:
    get:
      description: get posts by tags
      parameters:
      - description: page number
        in: query
        name: page
        required: true
        type: integer
      - description: page size
        in: query
        name: size
        required: true
        type: integer
      - description: tag ids
        in: query
        name: ids
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.Post'
            type: array
      summary: get posts by tags
      tags:
      - post
swagger: "2.0"
